id: I6AAAC7EF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T07:11:16+00:00'
last_modified: '2022-06-07T18:33:25.839123+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09766
  title: རྭ་སྟག་གི་དོན་རྐྱེན་དང་དེའི་ངོ་བོའི་སྐོར་གླེང་བ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    B60D:
      image_group_id: I00KG09847
      title: ''
      total_pages: 166
      order: 1
      base_file: B60D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
