id: P003234
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG09766
  title: རྭ་སྟག་གི་དོན་རྐྱེན་དང་དེའི་ངོ་བོའི་སྐོར་གླེང་བ་
  author: ''
  volumes:
    cc5b6a27d41247e7ae475522a763fce3:
      image_group_id: I00KG09847
      title: ''
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
